### ISSUE TITLE
Cloning to Heroku throws Socket.io Error

### ISSUE THREAD

**Issue by po456asd** [ypinskiy/GBF-Raiders#1]
https://zest-gbfraiders.herokuapp.com/
![image](https://user-images.githubusercontent.com/13596788/27974383-01a2b554-6388-11e7-8d7a-c8fb003c137b.png)

error 503 log in heroku
https://pastebin.com/fi2RVx6M

**Comment by po456asd** [comment]
log from try to restart app
https://pastebin.com/080tveSX

**Comment by ypinskiy** [comment]
That is an issue with a newer socket.io library. Run `npm install socket.io@1.3.5` to use an older version without that issue.

**Comment by po456asd** [comment]
Thanks you. ^^

**Comment by po456asd** [comment]
https://pastebin.com/Ef8Xy1TJ
still error
btw i use 
```
npm install socket.io@1.3.5
```
and try to see version with
```
npm list socket.io
```
it still be 2.0.3
![image](https://user-images.githubusercontent.com/13596788/27994057-1e2768ce-64e0-11e7-8d3e-08385337f864.png)


here when i try to install 1.3.5 log
https://pastebin.com/XiX0wZvU

**Comment by po456asd** [comment]
isn't it better to change socket.io in package.json from 
```
"socket.io": "^2.0.1",
```
to
```
"socket.io": "1.3.5",
```

**Comment by ypinskiy** [comment]
The new socket.io version works fine on newer versions of Node, I am using it just fine on both my test and production environments. Run `npm -v` and `node -v` and see if you can update them. On my test env I have

```
PS D:\Project Assets\GBF-Raiders> npm -v

5.0.3

PS D:\Project Assets\GBF-Raiders> node -v

v8.1.2
```

**Comment by ypinskiy** [comment]
You can delete the `npm_modules` folder, edit your local copy of `package.json` to use the older library and then run `npm install`.

_Sent from my LGE LG-H901 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by po456asd** [comment]
now i can't deploy to heroku anymore with this error
https://pastebin.com/hqqMFKQu

**Comment by ypinskiy** [comment]
Install gulp manually, install semantic-ui, then run npm install again.
Semantic-ui ran into an issue with their auto install script and you will
have to do the same steps manually.

**Comment by bosiddon** [comment]
I'm getting the same error with semantic-ui and even if I install gulp and semantic-ui manually that doesn't resolve the error.

**Comment by ypinskiy** [comment]
@bosiddon Just to confirm, you clone the project, install gulp, install semantic, and then  you get the 
```
/tmp/build_106a7b73bd8f17356b97cf4d5c67119f/ypinskiy-GBF-Raiders-49b4fb9/node_modules/semver/semver.js:295
       throw new TypeError('Invalid Version: ' + version);
       ^
       
       TypeError: Invalid Version: https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
```
error?

**Comment by ypinskiy** [comment]
I removed the code that causes that error in a recent commit anyway, so this won't be a problem in the future.

**Comment by po456asd** [comment]
```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  8.1.2
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 8.1.2...
       Downloading and installing node 8.1.2...
       Detected package-lock.json: defaulting npm to version 5.x.x
       Bootstrapping npm 5.x.x (replacing 5.0.3)...
       npm 5.3.0 installed
-----> Restoring cache
       Skipping cache restore (not-found)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       
       > semantic-ui@2.2.11 install /tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/semantic-ui
       > gulp install
       
       /tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/semver/semver.js:295
       throw new TypeError('Invalid Version: ' + version);
       ^
       
       TypeError: Invalid Version: https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
       at new SemVer (/tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/semver/semver.js:295:11)
       at compare (/tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/semver/semver.js:571:10)
       at Function.gt (/tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/semver/semver.js:600:10)
       at Liftoff.handleArguments (/tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/gulp/bin/gulp.js:99:14)
       at Liftoff.<anonymous> (/tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/liftoff/index.js:198:16)
       at module.exports (/tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/flagged-respawn/index.js:17:3)
       at Liftoff.<anonymous> (/tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/liftoff/index.js:190:9)
       at /tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/liftoff/index.js:164:9
       at /tmp/build_31df42478f18a5edc27140d86b24906e/ypinskiy-GBF-Raiders-360233a/node_modules/v8flags/index.js:93:14
       at FSReqWrap.oncomplete (fs.js:135:15)
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! semantic-ui@2.2.11 install: `gulp install`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the semantic-ui@2.2.11 install script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2017-08-01T05_25_35_579Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by ypinskiy** [comment]
First, install gulp manually with the `-g` flag to make it a global package. Then install semantic-ui again. Then try to deploy again.


_Sent from my Android XT1095 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
