### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by zhurai** [ypinskiy/GBF-Raiders#3]
This is the build log (off of clicking on the "Deploy to Heroku" button, and then inputting the key/secret keys from twitter and pressing "Deploy App")

> -----> Node.js app detected
> -----> Creating runtime environment
>        
>        NPM_CONFIG_LOGLEVEL=error
>        NPM_CONFIG_PRODUCTION=true
>        NODE_VERBOSE=false
>        NODE_ENV=production
>        NODE_MODULES_CACHE=true
> -----> Installing binaries
>        engines.node (package.json):  8.1.2
>        engines.npm (package.json):   unspecified (use default)
>        
>        Resolving node version 8.1.2...
>        Downloading and installing node 8.1.2...
>        Detected package-lock.json: defaulting npm to version 5.x.x
>        Bootstrapping npm 5.x.x (replacing 5.0.3)...
>        npm 5.4.1 installed
> -----> Restoring cache
>        Skipping cache restore (not-found)
> -----> Building dependencies
>        Installing node modules (package.json + package-lock)
>        
>        > semantic-ui@2.2.11 install /tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/semantic-ui
>        > gulp install
>        
>        /tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/semver/semver.js:295
>        throw new TypeError('Invalid Version: ' + version);
>        ^
>        
>        TypeError: Invalid Version: https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
>        at new SemVer (/tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/semver/semver.js:295:11)
>        at compare (/tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/semver/semver.js:571:10)
>        at Function.gt (/tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/semver/semver.js:600:10)
>        at Liftoff.handleArguments (/tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/gulp/bin/gulp.js:99:14)
>        at Liftoff.<anonymous> (/tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/liftoff/index.js:198:16)
>        at module.exports (/tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/flagged-respawn/index.js:17:3)
>        at Liftoff.<anonymous> (/tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/liftoff/index.js:190:9)
>        at /tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/liftoff/index.js:164:9
>        at /tmp/build_ce6603f36ffa53245bc022daa2183b3f/ypinskiy-GBF-Raiders-4ffb934/node_modules/v8flags/index.js:93:14
>        at FSReqWrap.oncomplete (fs.js:135:15)
>        npm ERR! code ELIFECYCLE
>        npm ERR! errno 1
>        npm ERR! semantic-ui@2.2.11 install: `gulp install`
>        npm ERR! Exit status 1
>        npm ERR!
>        npm ERR! Failed at the semantic-ui@2.2.11 install script.
>        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>        
>        npm ERR! A complete log of this run can be found in:
>        npm ERR!     /app/.npm/_logs/2017-09-10T10_24_43_409Z-debug.log
> -----> Build failed
>        
>        We're sorry this build is failing! You can troubleshoot common issues here:
>        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
>        
>        If you're stuck, please submit a ticket so we can help:
>        https://help.heroku.com/
>        
>        Love,
>        Heroku
>        
>  !     Push rejected, failed to compile Node.js app.
>  !     Push failed

**Comment by ypinskiy** [comment]
In Heroku, there is a menu option to run console commands directly. Try using that to install gulp manually first to make sure it installs and then try to deploy the app. Let me know if that doesn't work, I'll try something else.

**Comment by he4rtofcourage** [comment]
i'm having the same problem. i've updated gulp and tried installing it through the cli, got these errors:
```
peppy@peppy-PC MINGW64 /d/Projects/heroku/GBF-Raiders (master)
$ gulp -v
[06:36:07] CLI version 3.9.1
[06:36:07] Local version 3.9.1

peppy@peppy-PC MINGW64 /d/Projects/heroku/GBF-Raiders (master)
$ npm install gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> semantic-ui@2.2.13 install D:\Projects\heroku\GBF-Raiders\node_modules\semantic-ui
> gulp install

module.js:491
    throw err;
    ^

Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\heroku\GBF-Raiders\node_modules\global-prefix\index.js:12:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm WARN gbf-raider@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.2.13 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.2.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peppy\AppData\Roaming\npm-cache\_logs\2017-09-10T22_37_27_212Z-debug.log
```

**Comment by ypinskiy** [comment]
@he4rtofcourage what node and npm versions do you have?

**Comment by ypinskiy** [comment]
@zhurai mentioned in a Reddit post that this worked for them "I tried forking and connecting it to the fork on my own repo and it worked (i didn't do anything else). Previously i was attempting to use the purple "Deploy to heroku" which faces that error. I'm not sure why this happens though since I did not change the npm version after forking."

**Comment by he4rtofcourage** [comment]
yeah, i forked and deployed from my repo and now it works perfectly. deploying from the purple button still gives out errors.

**Comment by ypinskiy** [comment]
I might just delete that button after all this.
